import type {
  ProofPack,
  GeneratedProof,
  CritiqueIssue,
  CritiqueResult
} from "./types";

// Deterministic generator: the same input ProofPack always yields the same output.
// No timestamps, no randomness, no network calls.

export function generate(pack: ProofPack): GeneratedProof {
  const critique = critiquePack(pack);
  const markdown = renderMarkdown(pack, critique);
  const grantAnswer = renderGrantAnswer(pack);
  return { markdown, grantAnswer, critique };
}

// ------------------------------------------------------------------
// Critique
// ------------------------------------------------------------------

export function critiquePack(pack: ProofPack): CritiqueResult {
  const issues: CritiqueIssue[] = [];
  const claimIds = new Set(pack.claims.map((c) => c.id));
  const evidenceClaims = new Set<string>();
  for (const e of pack.evidence) for (const cid of e.supports) evidenceClaims.add(cid);

  const unmappedClaims = pack.claims
    .filter((c) => !pack.evidence.some((e) => e.supports.includes(c.id)))
    .map((c) => c.id);

  const unusedEvidence = pack.evidence
    .filter((e) => e.supports.length === 0 || e.supports.every((s) => !claimIds.has(s)))
    .map((e) => e.id);

  // Heuristic checks aligned with how grant reviewers actually read applications.
  if (!pack.profile.problem || pack.profile.problem.length < 40) {
    issues.push({
      severity: "block",
      field: "problem",
      message: "Problem statement is too short. Reviewers need to understand the pain point in 1-2 sentences."
    });
  }
  if (!pack.profile.impact) {
    issues.push({
      severity: "warn",
      field: "impact",
      message: "Quantify the impact if possible (time saved, error rate reduced, throughput)."
    });
  }
  if (!pack.profile.githubUrl && !pack.profile.demoUrl) {
    issues.push({
      severity: "block",
      field: "links",
      message: "Provide at least one inspectable artifact: GitHub repo or live demo URL."
    });
  }
  if (!pack.workflow.pipeline || pack.workflow.pipeline.length < 80) {
    issues.push({
      severity: "warn",
      field: "pipeline",
      message: "Describe the agent pipeline in more detail. Long-chain reasoning and multi-agent handoffs score higher."
    });
  }
  if (!pack.workflow.verification) {
    issues.push({
      severity: "warn",
      field: "verification",
      message: "Document how you verified agent output. Reviewers reward human verification gates."
    });
  }
  if (pack.claims.length < 3) {
    issues.push({
      severity: "info",
      field: "claims",
      message: "Three or more claims usually present a stronger application."
    });
  }
  for (const cid of unmappedClaims) {
    issues.push({
      severity: "block",
      field: `claim:${cid}`,
      message: `Claim ${cid} has no supporting evidence. Either add evidence or remove the claim.`
    });
  }
  for (const eid of unusedEvidence) {
    issues.push({
      severity: "info",
      field: `evidence:${eid}`,
      message: `Evidence ${eid} supports no claim. Map it to a claim or remove it.`
    });
  }

  // Score: start at 100, deduct by severity.
  let score = 100;
  for (const i of issues) {
    if (i.severity === "block") score -= 20;
    else if (i.severity === "warn") score -= 8;
    else score -= 2;
  }
  score = Math.max(0, Math.min(100, score));

  return { score, issues, unmappedClaims, unusedEvidence };
}

// ------------------------------------------------------------------
// Markdown rendering
// ------------------------------------------------------------------

function renderMarkdown(pack: ProofPack, critique: CritiqueResult): string {
  const lines: string[] = [];
  const { profile, workflow, claims, evidence, notes } = pack;

  lines.push(`# ${profile.name} — Proof Pack`);
  lines.push("");
  lines.push("> Generated by ProofChain. Each claim below links to inspectable evidence.");
  lines.push("");

  lines.push("## 1. Project");
  lines.push("");
  lines.push(`**Problem.** ${profile.problem}`);
  lines.push("");
  lines.push(`**Users.** ${profile.users}`);
  lines.push("");
  lines.push(`**Impact.** ${profile.impact}`);
  lines.push("");
  if (profile.githubUrl) lines.push(`- GitHub: ${profile.githubUrl}`);
  if (profile.demoUrl) lines.push(`- Live demo: ${profile.demoUrl}`);
  lines.push("");

  lines.push("## 2. AI-Assisted Workflow");
  lines.push("");
  lines.push(`**Tool.** ${workflow.tool}`);
  lines.push("");
  lines.push(`**Models.** ${workflow.models.join(", ")}`);
  lines.push("");
  lines.push(`**Pipeline.** ${workflow.pipeline}`);
  lines.push("");
  lines.push(`**Verification.** ${workflow.verification}`);
  lines.push("");

  lines.push("## 3. Claim Chain");
  lines.push("");
  lines.push("| ID | Claim | Confidence | Evidence |");
  lines.push("| --- | --- | --- | --- |");
  for (const c of claims) {
    const supporting = evidence
      .filter((e) => e.supports.includes(c.id))
      .map((e) => e.id)
      .join(", ");
    lines.push(`| ${c.id} | ${escapeCell(c.text)} | ${c.confidence} | ${supporting || "—"} |`);
  }
  lines.push("");

  lines.push("## 4. Evidence");
  lines.push("");
  for (const e of evidence) {
    const supports = e.supports.length ? e.supports.join(", ") : "—";
    const linkBit = e.url ? ` ([link](${e.url}))` : "";
    lines.push(`- **${e.id}** [${e.kind}] ${e.label}${linkBit} → supports: ${supports}`);
    if (e.note) lines.push(`  - ${e.note}`);
  }
  lines.push("");

  if (notes) {
    lines.push("## 5. Notes & Limitations");
    lines.push("");
    lines.push(notes);
    lines.push("");
  }

  lines.push("## 6. Reviewer Self-Check");
  lines.push("");
  lines.push(`- Score: **${critique.score}/100**`);
  lines.push(`- Unmapped claims: ${critique.unmappedClaims.length}`);
  lines.push(`- Unused evidence: ${critique.unusedEvidence.length}`);
  if (critique.issues.length) {
    lines.push("");
    lines.push("Issues flagged before submission:");
    for (const i of critique.issues) {
      lines.push(`- [${i.severity.toUpperCase()}] ${i.field}: ${i.message}`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

// ------------------------------------------------------------------
// Short grant-answer mode
// ------------------------------------------------------------------

function renderGrantAnswer(pack: ProofPack): string {
  const { profile, workflow, claims, evidence } = pack;
  const proofs = evidence
    .filter((e) => e.url)
    .map((e) => `${e.label}: ${e.url}`)
    .slice(0, 3)
    .join(" | ");

  const topClaims = claims
    .slice(0, 3)
    .map((c, i) => `(${i + 1}) ${c.text}`)
    .join(" ");

  const paragraph = [
    `${profile.name} addresses a real pain: ${profile.problem}`,
    `Users: ${profile.users}`,
    `Impact: ${profile.impact}`,
    `Built with ${workflow.tool} using ${workflow.models.join(", ")} models.`,
    `Pipeline: ${workflow.pipeline}`,
    `Verification: ${workflow.verification}`,
    `Core claims: ${topClaims}`,
    proofs ? `Public proof: ${proofs}` : ""
  ]
    .filter(Boolean)
    .join(" ");

  // Trim to ~1200 chars to fit common application length limits.
  if (paragraph.length <= 1200) return paragraph;
  return paragraph.slice(0, 1197) + "...";
}
